#!/usr/bin/env ruby
# frozen_string_literal: true

require 'thor'
require 'pry'

class ContextCLI < Thor
  # store different context (file for now)
  # add different notes to context
  # user can select a context and then type out a note

  desc 'add CONTEXT', 'create a new context'
  option new: :boolean
  option n: :boolean
  option add: :boolean
  option a: :boolean
  def context(*args)
    name = args.shift
    if options[:new] || options[:n]
      create_new_context(name)
      nil
    elsif options[:add] || options[:a]
      File.open("#{name}.md")
      add_to_context(name, args)
      nil
    else
      File.foreach("#{name}.md") { |line| puts line }
      nil
    end
  rescue Errno::ENOENT
    create_new_context(name, args)
  end

  private

  def create_new_context(name, args)
    File.new("#{name}.md", 'w')
    puts "Created context #{name}"
    add_to_context(name, args)
  end

  def add_to_context(name, args)
    File.open("#{name}.md", 'a') do |file|
      file.puts('* ' + args.join(' '))
      puts "Added '#{args.join(' ')}' to context #{name}"
    end
  end
end

ContextCLI.start(ARGV)
